### ISSUE TITLE
There's no licence

### ISSUE THREAD

**Issue by andrewswan** [stefanbirkner/picover#1]
I'm really interested in using this project, but I can't see any licence file. Would you mind if I raised a PR that added one? Do you have a [preference for which licence](https://choosealicense.com/)? If it's all the same to you, I'd prefer one of:

- Apache
- BSD
- MIT

**Comment by stefanbirkner** [comment]
Thank you for your interest in `picover`. It's licensed under the MIT license (see `pom.xml`). I add this information and improve the readme later on today.

**Comment by andrewswan** [comment]
Thanks mate, I didn't think to check in the POM, I only looked for a `LICENSE` file or similar.

**Comment by stefanbirkner** [comment]
I added a license file and in addition mentioned the license in the readme.
